image: epitechcontent/epitest-docker

build:
  stage: build
  script: 
    - ./compile-release.sh
  artifacts:
    paths:
      - ./build-*/bin
  cache:
    paths:
      - "*.o"

test:
  stage: test
  script:
    - (cd tests; ./tests.sh)
  dependencies:
    - build
